services:
  app:
    build: .
    command: python3 app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - PYTHONPATH:=/app
      - PYTHONUNBUFFERED=1
#    depends_on:
#      - prometheus
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#  grafana:
#    image: grafana/grafana:10.2.2
#    ports:
#      - 3000:3000
